/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 02:29:13 GMT 2023
 */

package org.jsoup.examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.examples.HtmlToPlainText;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.PseudoTextElement;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HtmlToPlainText_ESTest extends HtmlToPlainText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Document document0 = Document.createShell("\n\"OLncm-s=>?#}&(t!g^");
      Element element0 = document0.text("\n\"OLncm-s=>?#}&(t!g^");
      element0.appendTo(document0);
      // Undeclared exception!
      htmlToPlainText0.getPlainText(document0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Document document0 = Document.createShell("s+");
      Document document1 = (Document)document0.text("\n");
      document1.prepend("\nm");
      document1.normalise();
      String string0 = htmlToPlainText0.getPlainText(document1);
      assertEquals(" m ", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      ParseSettings parseSettings0 = new ParseSettings(true, true);
      Tag tag0 = Tag.valueOf("a", parseSettings0);
      Element element0 = new Element(tag0, "a");
      String string0 = htmlToPlainText0.getPlainText(element0);
      assertEquals(" <>", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Tag tag0 = Tag.valueOf("h3");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "h3", attributes0);
      String string0 = htmlToPlainText0.getPlainText(element0);
      assertEquals("\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("dt", parseSettings0);
      Attributes attributes0 = new Attributes();
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "t[e3", attributes0);
      String string0 = htmlToPlainText0.getPlainText(pseudoTextElement0);
      assertEquals("  \n", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Element element0 = new Element("li");
      String string0 = htmlToPlainText0.getPlainText(element0);
      assertEquals("\n * ", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
      Document document0 = Document.createShell("s+");
      Element element0 = document0.text("\n");
      String string0 = htmlToPlainText0.getPlainText(element0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // usage: java -cp jsoup.jar org.jsoup.examples.HtmlToPlainText url [selector]
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must supply a valid URL
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must supply a valid URL
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
