/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 01:52:47 GMT 2023
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.BooleanAttribute;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BooleanAttribute_ESTest extends BooleanAttribute_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BooleanAttribute booleanAttribute0 = new BooleanAttribute("formnovalidate");
      boolean boolean0 = booleanAttribute0.isBooleanAttribute();
      assertTrue(boolean0);
  }
}
