/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 02:32:19 GMT 2023
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.HttpStatusException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpStatusException_ESTest extends HttpStatusException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 1548, "");
      String string0 = httpStatusException0.toString();
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: . Status=1548, URL=", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 1548, "");
      int int0 = httpStatusException0.getStatusCode();
      assertEquals(1548, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 0, "");
      String string0 = httpStatusException0.getUrl();
      assertEquals("", string0);
  }
}
