/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 19 02:08:48 GMT 2023
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.UnsupportedMimeTypeException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnsupportedMimeTypeException_ESTest extends UnsupportedMimeTypeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnsupportedMimeTypeException unsupportedMimeTypeException0 = new UnsupportedMimeTypeException("!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv");
      String string0 = unsupportedMimeTypeException0.getMimeType();
      assertEquals("!LwZntFG9B^6>Zx0rv", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnsupportedMimeTypeException unsupportedMimeTypeException0 = new UnsupportedMimeTypeException("!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv");
      String string0 = unsupportedMimeTypeException0.toString();
      assertEquals("org.evosuite.runtime.mock.java.lang.MockThrowable: !LwZntFG9B^6>Zx0rv. Mimetype=!LwZntFG9B^6>Zx0rv, URL=!LwZntFG9B^6>Zx0rv", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnsupportedMimeTypeException unsupportedMimeTypeException0 = new UnsupportedMimeTypeException("!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv", "!LwZntFG9B^6>Zx0rv");
      String string0 = unsupportedMimeTypeException0.getUrl();
      assertEquals("!LwZntFG9B^6>Zx0rv", string0);
  }
}
